CREATE TABLE "EventoRelatado" (
	"idRelato" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"Data" INTEGER,
	"Localização" INTEGER,
	"Tipo" INTEGER,
	PRIMARY KEY("idRelato")
) INHERITS ("Usuário");


CREATE INDEX "Evento Relatado_index_0"
ON "EventoRelatado" ();

CREATE TABLE "Usuário" (
	"CPF" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"Nome" VARCHAR(255),
	"Telefone" INTEGER,
	"email" VARCHAR(255),
	PRIMARY KEY("CPF")
);




CREATE TABLE "RelatorioUsuario" (
	"idRelatorio" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"descricao" ,
	"data" ,
	"foto" ,
	PRIMARY KEY("idRelatorio")
);



ALTER TABLE "Usuário"
ADD FOREIGN KEY("CPF") REFERENCES "RelatorioUsuario"("idRelatorio")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "RelatorioUsuario"
ADD FOREIGN KEY("idRelatorio") REFERENCES "EventoRelatado"("idRelato")
ON UPDATE NO ACTION ON DELETE NO ACTION;